### ISSUE TITLE
 Failed due to an ERR_INVALID_ARG_TYPE error (undefined)

### ISSUE THREAD

**Issue by diogoredin** [rudderlabs/rudder-typer#72]
## Description

- Error: ` Failed due to an ERR_INVALID_ARG_TYPE error (undefined). Error: Unable to write ruddertyper.yml`
- Version 1.0.0 of RudderTyper
- Node v20.17.0

**Settings:**
- Typescript
- Web (analytics.js)
- Selected tracking plan
- Development
- `src/apps/web`

![Screenshot 2024-09-30 at 11 24 55](https://github.com/user-attachments/assets/20d8924d-34d5-472d-b122-f98970286eda)
![Screenshot 2024-09-30 at 11 25 29](https://github.com/user-attachments/assets/c0b0b626-3565-43ad-aabf-1a766f548601)

**Comment by akashrpo** [comment]
Hi @diogoredin, thank you for reporting this issue.

We have just released a new version of RudderTyper, v1.1.0, which includes several updates. Could you please update to this version and try again with the same configuration? I tested it with the settings you provided, and it seems to work for me.

If the issue persists, please let me know, and we can dig further into it together.

**Comment by nickmeewis** [comment]
I experienced the same with version V1.1.0 but after updating node to v20.11.1 the problem was resolved
